// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {defineConfig} from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "ts-node prisma/seed.ts",
    },
    datasource: {
        // Migrations go through a DIRECT (non-pooled) connection when provided:
        // PgBouncer in transaction mode breaks the session-level advisory lock
        // used by `migrate deploy` (P1002), and a sleeping Neon doesn't fit
        // into the 10s lock timeout. Runtime (PrismaPg adapter with
        // DATABASE_URL) keeps using the pooler — this setting affects CLI only.
        url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
    },
});